### ISSUE TITLE
Documentation on libdexterity.so

### ISSUE THREAD

**Issue by strangeloveBsc** [rchiossi/dexterity#10]
I know it's been a while since this project has been touched but while it's being a side result of the code: Is it possible to get something like a usage example or API documentation on libdexterity?

I was looking for a Dex-Parser in C and it was the closest I got, but I am having a hard time trying to use the lib for a project.

Thanks in advance!

**Comment by rchiossi** [comment]
I believe your best option is to get the examples form python code. The mapping from C to python is 1:1.  The file dx/dxlib.py gives you the mapping from C to python, so you can check there how the python code is being converted to C. The port should be straight forward.
Let me know if you need help with that. It's been a while since I last worked on this, I may need to refresh my memory... ;)

**Comment by strangeloveBsc** [comment]
Thanks, after spending a few more hours on the Dex-Format I noticed that the code is pretty self-explanatory as soon as one knows what it does.
I guess the Macros threw me off a bit ^^"
